# Functions for analysis

# Function to read the fasta files with the sequencing reads
import_reads <- 
  function(sample_name, suffix){
    sample_name <- paste0(suffix, sample_name)
    test_data <- readDNAStringSet(sample_name)
    id_reads <- names(test_data)
    id_reads <-
      as_tibble(matrix(unlist(strsplit(id_reads, ';')), ncol = 2, byrow = T))
    id_reads$sequence <- as.character(test_data)
    colnames(id_reads) <- c('id', 'number', 'sequence')
    
    id_reads$number <-
      gsub(pattern = 'size=', replacement = '', id_reads$number)
    
    return(id_reads)
  }


# Function to get the number of generation using the OD values recorderd at each timepoint
get_generation <- 
  function(end_od, start_od = 0.1){
    x <- start_od
    g = 0
    while (x < end_od) {
      g = g+1
      if(x*2 < end_od){
        x <- x*2 
        next
      } else if(x*2 >= end_od){
        dif <- end_od - x
        g <- g + dif/x
        return(g)
        break
      }
    }
  }


# Functions to generate correlation plots
my_scatter_double_layer <- function(data, mapping, ...) {
  ggplot(data = data, mapping = mapping) +
    # First layer: all points, in light gray
    geom_point(size =0.2 , ) +
    scale_color_manual(values= c( 'darkgrey', 'red'))+
    # Second layer: only group A, highlighted
    geom_point(data = subset(data, ref_family), 
               aes(x = !!mapping$x, y = !!mapping$y), 
               color = "red", size =0.2) +
    # Identity line
    geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
    theme_void()+
    theme(
      panel.border = element_rect(color = "black", fill = NA, linewidth = 1)
    )
}

my_cor <- function(data, mapping, ...) {
  x <- eval_data_col(data, mapping$x)
  y <- eval_data_col(data, mapping$y)
  r_val <- cor(x, y, use = "complete.obs")
  ggplot(data = data, mapping = mapping) +
    annotate("text", x = mean(range(x, na.rm = TRUE)), 
             y = mean(range(y, na.rm = TRUE)), 
             label = sprintf("%.2f", r_val),
             size = 3, color = "black") +
    theme_void()+
    theme(
      panel.border = element_rect(color = "black", fill = NA, linewidth = 1)
    )
}

my_diag <- function(data, mapping, ...) {
  var_name <- as_label(mapping$x)
  ggplot(data = data, mapping = mapping) +
    annotate("text", x = 0.5, y = 0.5, label = var_name, size = 3) +
    theme_void()+
    theme(
      panel.border = element_rect(color = "black", fill = NA, linewidth = 1)
    )
}


# function to compute standard deviation per aa_sequence
#+++++++++++++++++++++++++
# Function to calculate the mean and the standard deviation
# for each group
#+++++++++++++++++++++++++
# data : a data frame
# varname : the name of a column containing the variable
#to be summariezed
# groupnames : vector of column names to be used as
# grouping variables
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
  return(data_sum)
}


# Function to compute the PWM score for all sequences generated by degenerating one position in the PWM
get_PWM_score <-
  function(sub_PWM, deg_pos) {
    seq <- ''
    score <- 0
    
    for (i in 1:nrow(sub_PWM)) {
      
      if (i %in% c(deg_pos$pos1)) {
        print('deg1')
        
        aa <- colnames(sub_PWM[i, ])
        part_score <- unlist(sub_PWM[i, ])
        #print(aa)
        seq <- str_c(seq, aa)
        #print(part_seq)
        score <- score + part_score
        
      }
      
      if (i %in% c(deg_pos$pos2)) {
        print('deg2')
        
        aa <- colnames(sub_PWM[i, ])
        aa <- rep(aa, length.out = length(seq) * 20)
        part_score <- unlist(sub_PWM[i, ])
        part_score <- rep(part_score, length.out = length(seq) * 20)
        
        seq <- rep(seq, each = 20)
        score <- rep(score, each = 20)
        
        seq <- str_c(seq, aa)
        score <- score + part_score
        
      }
      
      if (i %in% c(deg_pos$pos)) {
        print('deg2')
        
        aa <- colnames(sub_PWM[i, ])
        aa <- rep(aa, length.out = length(seq) * 20)
        part_score <- unlist(sub_PWM[i, ])
        part_score <- rep(part_score, length.out = length(seq) * 20)
        
        seq <- rep(seq, each = 20)
        score <- rep(score, each = 20)
        
        seq <- str_c(seq, aa)
        score <- score + part_score
        
      }
      
      if (!(i %in% c(deg_pos$pos1, deg_pos$pos2, deg_pos$pos))) {
        aa <- max.col(sub_PWM, ties.method = 'first')[i]
        part_score <- unlist(sub_PWM[i, aa])
        part_seq <- colnames(sub_PWM)[aa]
        seq <- str_c(seq, part_seq)
        score <- score + part_score
      }
      
    }
    
    score_out <-
      tibble(
        family = unique(deg_pos$family),
        aa_seq = seq,
        PWM_score = score
      )
    return(score_out)
  }


# get the stickiness score using the Levy 2014 stikiness scale
get_stickyness <- function(list_aa, sticky, absolute = TRUE){
  table_aa <- table(list_aa)
  
  table_aa <- as.data.frame(table_aa)
  sticky_aa <- 
    merge(table_aa, 
          sticky, 
          by.x = 'list_aa', 
          by.y = 'AA')
  
  sticky_aa <- mutate(sticky_aa, score_aa = Freq*sticky_score)
  
  if(absolute){
  sticky_prot <- sum(sticky_aa$score_aa)
  } else{
    sticky_prot<-sum(sticky_aa$score_aa)/sum(sticky_aa$Freq)
  }
  
  
  return(sticky_prot)
}

# set theme for figures
t <- theme_classic2()+
  theme(axis.title = element_text(size = 10, color = 'black'), 
        axis.text = element_text(size = 8, color = 'black'), 
        axis.line = element_line(linewidth = 0), 
        axis.ticks = element_line(linewidth = 0.8),
        legend.title = element_text(size = 10, color = 'black'), 
        legend.text = element_text(size = 8, color = 'black'), 
        panel.border = element_rect(color = "black", 
                                    fill = NA,
                                    size = 0.8))

# extract maximal peptide from mutagenesis data
peptide_max <-
  function(df){
    df%>%
      select(family, pool, pos_value, deg_value, signif, side) %>%
      select(family, pool, pos_value, deg_value) %>%
      group_by(family, pool, pos_value) %>%
      pivot_wider(names_from = pos_value, values_from = deg_value) ->inter_pos
    
    # Reorder columns by the numeric value in their name (except for the first columns)
    col_names <- colnames(inter_pos)
    # Assume first columns are 'family' and 'pool', rest are positions
    fixed_cols <- c("family", "pool")
    pos_cols <- setdiff(col_names, fixed_cols)
    # Extract numeric part and order
    pos_cols_ordered <- pos_cols[order(as.numeric(pos_cols))]
    inter_pos <- inter_pos[, c(fixed_cols, pos_cols_ordered)]
    
    inter_pos%>%
      select(family, pool, everything()) %>%
      arrange(family, pool) -> inter_pos
    
    
    return(inter_pos)
  }

get_foldchange <- 
  function(df, repli = c('R1', 'R2', 'R3'), reads = 20){
    for( r in repli){
      z <- df[, c(1, grep(r, colnames(df)))]
      
      tot_reads <- colSums(z[, grep('T', colnames(z))], na.rm = T)
     
      t0<-colnames(z)[grep('T0', colnames(z))]


      z %<>%
      filter(get(t0) >= reads)%>%
        mutate(across(
          all_of(names(tot_reads)),
          ~ . / tot_reads[cur_column()],
          .names = "freq_{.col}"
        ))
      
      name_rep <- colnames(z)[grep('T0_', colnames(z))[1]]
      name_rep <-
        str_c(unlist(strsplit(name_rep, '_'))[2:4], collapse = '_')
      
      col1 <- str_c(c(name_rep, 'foldchange_T1'), collapse = '_')
      col2 <- str_c(c(name_rep, 'foldchange_T2'), collapse = '_')
      
      
      c1 <- tibble(log2(z[, grep('freq_T1.', colnames(z))] / z[, grep('freq_T0.', colnames(z))]))
      colnames(c1) <- col1
      
      c2 <- tibble(log2(z[, grep('freq_T2.', colnames(z))] / z[, grep('freq_T0.', colnames(z))]))
      colnames(c2) <- col2
   
      assign(r, bind_cols('sequence' = z$sequence, c1, c2))
    }
    
    foldchange <- 
      left_join(df, R1)
    
    foldchange <- 
      left_join(foldchange, R2)  
    
    foldchange <- 
      left_join(foldchange, R3)  

    return(foldchange)
  }

get_foldchange_per_condition <- 
  function(df, reads = 20){
    condition2 <-  colnames(df)[grep('T', colnames(df))]
    
    n_con <- 
      unique(unlist(lapply(strsplit(condition2, '_'), `[[`, 5)))
    
    if(length(n_con)==2){
      
      f <- get_foldchange(df)
      return(f)
      }
    
    if(length(n_con)>2){
      
      b <- grep('Both', colnames(df))
      d <- grep('DMSO', colnames(df)) 
      m <- grep('MTX', colnames(df))
      
      d <- df[, c(1:3, b, d)]
      m <- df[, c(1:3, b, m)]
      
      d <- get_foldchange(d, reads = reads)
      m <- get_foldchange(m, reads =reads)
      
      name_d <- grep('fold', colnames(d))
      name_m <- grep('fold', colnames(m))
      
      colnames(d)[name_d] <- 
        paste0(colnames(d)[name_d], '_DMSO')
      
      colnames(m)[name_m] <- 
        paste0(colnames(m)[name_m], '_MTX')
      
      dm <- 
        full_join(d, m[, -c(4:12)])
      
      return(dm)
    }
  }

  long_foldchange <- 
  function(df){
    fc_cols <- 
      grep('foldchange', colnames(df))
    
    sub_df <- df[, c(1:3, fc_cols)]
    
    long_df <- 
      pivot_longer(sub_df,
                   cols = 4:ncol(sub_df), 
                   names_to = c('pool', 'replicate', 'assay', 'measure', 'timepoint_end', 'condition'), 
                   names_sep = '_', values_to = 'delta')
  }


get_selcoef <- 
function(df, sample_gen){
    
  n <- unique(df$pool)
    
    pool_gen <- sample_gen[sample_gen$Pool == n ,]
    
    if(unique(is.na(df$condition))){
      df <- 
        merge(df, 
              pool_gen[, -c(2,3)], 
              by.x = c('replicate', 'timepoint_end'), 
              by.y = c('replicate', 'timepoint'))
      
    }
    else if(!unique(is.na(df$condition))){
      df <- 
        merge(df, 
              pool_gen[, -c(2)], 
              by.x = c('replicate', 'timepoint_end', 'condition'), 
              by.y = c('replicate', 'timepoint', 'condition'))
      
    }
    
    df%<>%
      mutate(sel_coef = delta/n_gen)
    
    return(df)
}


get_norm_selcoef <- 
  function(df, ref_df, time = 'T2'){

assay <- unique(df$assay)

if (assay == 'Avail'){

  ref_seq <- c('pdz.2','250_4')
  pos <- c('pdz.2')
  neg <- c('250_4')
  
} else if (assay == 'PPI'){
  
  ref_seq <- c('250_3','sh3.1')
  neg <- c('250_3')
  pos <- c('sh3.1')
   
}

ref_df %>%
    dplyr::filter(family %in% ref_seq & timepoint_end == time)%>%
    select(replicate, family, sel_coef, condition) -> ref_df

# Transform reference dataframe to wide format: each family becomes a column of selection coefficients
pivot_wider(ref_df, values_from = sel_coef, names_from = family)->ref_df

npos <- 
  sum(colnames(ref_df) %in% pos)

pos_col <-  paste0('pos', 1:npos)

nneg <-  sum(colnames(ref_df) %in% neg)
neg_col <- paste0('neg', 1:nneg)


colnames(ref_df)[colnames(ref_df) %in% pos] <- pos_col
colnames(ref_df)[colnames(ref_df) %in% neg] <-neg_col


# compute mean values for the references
ref_df%<>%
  dplyr::group_by(replicate, condition)%>%
  dplyr::mutate(neg_ref = rowMeans(across(all_of(neg_col)), na.rm = TRUE), 
                pos_ref =rowMeans(across(all_of(pos_col)), na.rm = TRUE))

# merge data with the references
df <- 
  merge(df[df$timepoint_end == time, ], 
        ref_df[, c('replicate', 'neg_ref', 'pos_ref', 'condition')], 
        by = c('replicate', 'condition'))


# compute scaling to ref values
df%<>%
  mutate(norm_sel_coef = (sel_coef - neg_ref)/(pos_ref - neg_ref))

return(df)
}


cor_plot<- 
function(df, p, time = 'T2', just_norm = FALSE, file_dir, file_name){
  
df%>%
  dplyr::filter(pool == p)->pool_df

pool_df$replicate<-factor(pool_df$replicate, 
                    levels = c('R1', 'R2', 'R3'))

if(!just_norm){
replicate_check_sel<- 
pool_df%>%
filter(timepoint_end == time)%>%
select(replicate, condition, aa_seq, sequence, family, timepoint_end, pool, sel_coef)%>%
  pivot_wider(
              names_from = replicate, 
              values_from = sel_coef, values_fn = unique)
}

replicate_check_norm_sel<- 
  pool_df%>%
  filter(timepoint_end == time)%>%
  select(replicate, condition, aa_seq, sequence, family, timepoint_end, pool, norm_sel_coef)%>%
  pivot_wider(
              names_from = replicate, 
              values_from = norm_sel_coef, values_fn = unique)


if(p %in% c('P1', 'P2')){
ref_seq<-c("pdz.1", "pdz.2","sh3.1","sh3.2","304_1","250_4","304_4", '366_3')

} else if(p %in% c('P3', 'P4', 'P5', 'P6')){
  ref_seq<-c("pdz.1", "pdz.2","sh3.1","sh3.2", "299_1", "250_3","363_4",  "152_2")
}


replicate_check_norm_sel[replicate_check_norm_sel$family %in% ref_seq, 'ref_family'] <- TRUE
replicate_check_norm_sel$ref_family <- replace_na(replicate_check_norm_sel$ref_family, replace = FALSE)

replicate_check_norm_sel[replicate_check_norm_sel$ref_family, 'alpha_val'] <- 1
replicate_check_norm_sel[!replicate_check_norm_sel$ref_family, 'alpha_val'] <- 0.1

if(!just_norm){
replicate_check_sel[replicate_check_sel$family %in% ref_seq, 'ref_family'] <- TRUE
replicate_check_sel$ref_family <- replace_na(replicate_check_sel$ref_family, replace = FALSE)

replicate_check_sel[replicate_check_sel$ref_family, 'alpha_val'] <- 1
replicate_check_sel[!replicate_check_sel$ref_family, 'alpha_val'] <- 0.1
}

# Use custom function to generate correlation graph between replicates

if(length(unique(replicate_check_norm_sel$condition))>1){
  
  cond <- 'MTX'
  MTX <- 
    ggpairs(replicate_check_norm_sel[replicate_check_norm_sel$condition == cond, ], columns = 7:9,
            # Replace with your actual replicate columns
            mapping = aes(color = ref_family, alpha = alpha_val),
    upper = list(continuous = my_cor),
    lower = list(continuous = my_scatter_double_layer),
    diag  = list(continuous = my_diag))+  
    theme(strip.background = element_blank(), 
          strip.text = element_blank(), 
          plot.margin = margin(t = 5,  # Top margin
                               r = 5,  # Right margin
                               b = 5,  # Bottom margin
                               l = 20), unit = 'mm') # Left margin)
  
  ggsave(paste0(file_dir, p, '_', cond, '_norm_', file_name, '.png'), MTX, height = 4, width = 4)
  
  if(!just_norm){
  cond <- 'DMSO'
  DMSO <- 
    ggpairs(replicate_check_sel[replicate_check_sel$condition == cond, ], columns = 7:9,
            # Replace with your actual replicate columns
            mapping = aes(color = ref_family, alpha = alpha_val),
    upper = list(continuous = my_cor),
    lower = list(continuous = my_scatter_double_layer),
    diag  = list(continuous = my_diag))+
    theme(strip.background = element_blank(), 
          strip.text = element_blank(), 
          plot.margin = margin(t = 5,  # Top margin
                               r = 5,  # Right margin
                               b = 5,  # Bottom margin
                               l = 20), unit = 'mm') # Left margin)
  
  ggsave(paste0(file_dir ,p, '_', cond, '_', file_name, '.png'), DMSO, height = 4, width = 4)
  }
} else {
  
  P <- 
    ggpairs(replicate_check_norm_sel, columns = 7:9,
            # Replace with your actual replicate columns
            mapping = aes(color = ref_family, alpha = alpha_val),
    upper = list(continuous = my_cor),
    lower = list(continuous = my_scatter_double_layer),
    diag  = list(continuous = my_diag))+
    theme(strip.background = element_blank(), 
          strip.text = element_blank(), 
          plot.margin = margin(t = 5,  # Top margin
                               r = 5,  # Right margin
                               b = 5,  # Bottom margin
                               l = 20), unit = 'mm') # Left margin)
  
  ggsave(paste0(file_dir, p, '_norm_', file_name, '.png'), P, height = 4, width = 4)
  
  if(!just_norm){
  P <- 
    ggpairs(replicate_check_sel, columns = 7:9,
            # Replace with your actual replicate columns
            mapping = aes(color = ref_family, alpha = alpha_val),
            upper = list(continuous = my_cor),
            lower = list(continuous = my_scatter_double_layer),
            diag  = list(continuous = my_diag))+
    theme(strip.background = element_blank(), 
          strip.text = element_blank(), 
          plot.margin = margin(t = 5,  # Top margin
                               r = 5,  # Right margin
                               b = 5,  # Bottom margin
                               l = 20), unit = 'mm') # Left margin)
  
  ggsave(str_c(file_dir, p, '_',file_name, '.png'), P, height = 4, width = 4)
  }
  
}
}


stat_comp_intra_family <- function(df, vec_family, welch = TRUE, metric = 'norm_sel_coef') {
  signif_all <- tibble()
  for (family in vec_family){
    
    sub_sel_coef <- df[df$family == family, ]
   
    sub_sel_coef %<>%
    group_by(aa_seq) %>%
    drop_na(norm_sel_coef)%>%
    filter(n() >= 2) %>%  # must have 2 groups
    ungroup()

     aa_to_compare <- 
      unique(sub_sel_coef$aa_seq)
    
    aa_ref <- 
    unlist(unique(sub_sel_coef[sub_sel_coef$peptide_max, 'aa_seq' ]))
    
    colnames(sub_sel_coef)[colnames(sub_sel_coef)==metric]<-'metric'
    
    aa_seq_stat <- 
      t_test(sub_sel_coef, metric ~ aa_seq, ref.group = aa_ref, var.equal = !welch, 
      p.adjust.method = 'BH')
    
   
    signif_diff<-  aa_seq_stat[aa_seq_stat$p.adj.signif != 'ns', 'group2']
    
    stronger <- signif_diff$group2 %in% unlist(aa_seq_stat[aa_seq_stat$statistic < 0 & aa_seq_stat$p.adj.signif != 'ns', 'group2'])
    weaker <- signif_diff$group2 %in% unlist(aa_seq_stat[aa_seq_stat$statistic > 0 & aa_seq_stat$p.adj.signif != 'ns', 'group2'])
    
    signif_diff$family <- family
    signif_diff[weaker, 'side'] <- 'weaker'
    signif_diff[stronger, 'side'] <- 'stronger'
    
    signif_all <- bind_rows(signif_all, signif_diff)
  
    
  }
  return(signif_all)
}

# function to compute the score of all peptide obtained by degenerating 2 positions
position_score<-
function(deg_pos, sub_PWM, score = 0, seq ='') {
 for (i in 1:nrow(sub_PWM)) {   

      if (i %in% c(deg_pos$pos1)) {
        #print('deg1')
        
        aa <- colnames(sub_PWM[i, ])
        part_score <- unlist(sub_PWM[i, ])
        #print(aa)
        seq <- str_c(seq, aa)
        #print(part_seq)
        score <- score + part_score
        
      }
      
      if (i %in% c(deg_pos$pos2)) {
        #print('deg2')
        
        aa <- colnames(sub_PWM[i, ])
        aa <- rep(aa, length.out = length(seq) * 20)
        part_score <- unlist(sub_PWM[i, ])
        part_score <- rep(part_score, length.out = length(seq) * 20)
        
        seq <- rep(seq, each = 20)
        score <- rep(score, each = 20)
        
        seq <- str_c(seq, aa)
        score <- score + part_score
        
      }
      
      if (i %in% c(deg_pos$pos)) {
        #print('deg2')
        
        aa <- colnames(sub_PWM[i, ])
        aa <- rep(aa, length.out = length(seq) * 20)
        part_score <- unlist(sub_PWM[i, ])
        part_score <- rep(part_score, length.out = length(seq) * 20)
        
        seq <- rep(seq, each = 20)
        score <- rep(score, each = 20)
        
        seq <- str_c(seq, aa)
        score <- score + part_score
        
      }
      
      if (!(i %in% c(deg_pos$pos1, deg_pos$pos2, deg_pos$pos))) {
        aa <- max.col(sub_PWM, ties.method = 'first')[i]
        part_score <- unlist(sub_PWM[i, aa])
        part_seq <- colnames(sub_PWM)[aa]
        seq <- str_c(seq, part_seq)
        score <- score + part_score
      }

 }
  return(list(score, seq))
 
}


get_PWM_score <-
  function(sub_PWM, deg_pos, n) {
    seq <- ''
    score <- 0
    score_out<-tibble()

    for(r in 1:nrow(deg_pos)){
      info_score <- position_score(deg_pos[r, ], sub_PWM)
      score_out <- bind_rows(score_out, tibble(score = info_score[[1]], aa_seq = info_score[[2]]))
    }

    return(unique(score_out))
  }


get_PWM_from_seq<-
  function(sequence, sub_PWM) {
    score <- 0
    seq_split <- strsplit(sequence, "")[[1]]
    for (i in seq_along(seq_split)) {
      aa <- seq_split[i]
      if (aa %in% colnames(sub_PWM)) {
        score <- score + sub_PWM[i, aa]
      } else {
        score <- NA
        break
      }
    }
    return(score)
  }